ship_o_cereal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('cereal.urls')),
    path('admin/', admin.site.urls),
    path('cereals/', include('cereal.urls')),
    path('checkout/', include('checkout.urls')),
    path('payment/', include('payment.urls')),
    path('review/', include('review.urls')),
    path('user/', include('user.urls')),
    path('cart/', include('cartapp.urls'))
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout', LogoutView.as_view(next_page='login'), name='logout'),
    path('profile', views.profile, name='profile'),

]

cereal/models.py
from django.db import models

# Create your models here.
class CerealCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name



class Cereal(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    category = models.ForeignKey(CerealCategory, on_delete=models.CASCADE)
    price = models.FloatField()
    is_merch = models.BooleanField()

    def __str__(self):
        return self.name



class CerealImage(models.Model):
    image = models.CharField(max_length=9999, blank=True)
    cereal = models.ForeignKey(Cereal, on_delete=models.CASCADE)

templates/cart/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% include 'navigation.html' %}
    <div class="container top-margin">
        <div class="opacity-info white-text">
            <div class="row">
                <h1 class="col-md-2" style="text-align: center;">Your cart</h1>
            </div>
            <div class="row">
                <h4 class="col-md-2" style="text-align: center;">Image</h4>
                <h4 class="col-md-2">Description</h4>
                <h4 class="col-md-1">Price</h4>
                <h4 class="col-md-1">Quantity</h4>
                <h4 class="col-md-1">Remove</h4>
            </div>
            <div>
                {% for item in cart %}
                {% include 'cart/single_item.html' with item=item %}
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-md-2">
                    <div class="btn" style="background-color:green; margin-left: 50px; margin-top: 20px;">
                        <a style="color:white;" href="{% url 'cereal-index'%}">Back to catalogue</a>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="btn" style="background-color:green; margin-left: 750px; margin-top: 20px;">
                        <a style="color:white;" href="{% url 'contact-index'%}">Proceed to checkout</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/cart/single_item.html
{% load static %}
<div class="row">
    <div class="col-md-2">
        <a href="/">
            {% if item.IdCereal.cerealimage_set.first.image != "" %}
                <img src={{ item.IdCereal.cerealimage_set.first.image }} class="float-left">
            {% else %}
                <img src="https://pbs.twimg.com/profile_images/1155645244563742721/tuCu6BT-.jpg" class="float-left">
            {% endif %}
        </a>
    </div>
    <div class="col-md-2">
        <div>
            <p>{{ item.IdCereal.description }}</p>
        </div>
    </div>
    <div class="col-md-1">
        <div>
            <p>${{ item.IdCereal.price }}</p>
        </div>
    </div>
    <div class="col-md-1">
        <div>
            <p>{{ item.CerealAmount }}</p>
        </div>
    </div>
    <div class="col-md-1">
        <div class="btn" style="text-align: center; display:inline">
            <div class="btn" style="color:white; background-color:red; width: 50%;">
                <a style="color:white;" href="{% url 'cart-remove' item.IdCereal.pk %}">X</a>
            </div>
        </div>
    </div>
</div>